name: Check PR
on:
  pull_request:
    paths:
      - curricula.yaml
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm i
      - run: npm run build
        env:
          CURRICULUM_FILE_URL: ${{ secrets.CURRICULUM_FILE_URL }}
          CURRICULUM_SITE_URL: ${{ secrets.CURRICULUM_SITE_URL }}
