name: Check PR
on:
  pull_request:
	paths:
	  - curricula.yaml
	branch:
	  - master
jobs:
  build:
	runs-on: ubuntu-latest
	steps:
	  - uses: actions/checkout@v4
	  - uses: actions/setup-node@v4
		with:
		  node-version: '22'
	  - run: npm ci
	  - run: npm run build
		env:
		  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
		  R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
		  R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
